# Generated by Django 2.0.3 on 2018-04-17 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='cellphone',
            new_name='phone',
        ),
    ]
