# Generated by Django 2.0.3 on 2018-04-20 13:01

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180417_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
